title: Art Progress & Studies
author: HenryBear64
email: Henrybear18@outlook.com
description: > 
This is a site where I will post my sketches, to see my progress. I'm a FreeLancer Coder and Illustrator.

# social links
twitter_username: Henry_Bear_X
github_username:  HenryBear64

show_excerpts: true 
theme: minima